"use client";
import { FormEvent, useState } from "react";
import { AppWindow, KeyRound, Laptop, Link2, ShieldCheck, UserRound } from "lucide-react";
import { authClient } from "@/lib/auth-client";
import { PermissionRevoke } from "@/components/permission-revoke";

type Account={id:string;providerId:string;createdAt:string};
type DeviceSession={id:string;token:string;userAgent:string|null;ipAddress:string|null;createdAt:string;expiresAt:string;current:boolean};
type Permission={id:string;name:string;scopes:string[];updatedAt:string};

export function AccountCenter({name,email,accounts,sessions,permissions}:{name:string;email:string;accounts:Account[];sessions:DeviceSession[];permissions:Permission[]}) {
  const [notice,setNotice]=useState<string|null>(null);
  const [busy,setBusy]=useState(false);
  async function updateProfile(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setNotice(null);const newName=String(new FormData(event.currentTarget).get("name")??"");const result=await authClient.updateUser({name:newName});setNotice(result.error?(result.error.message??"Profil güncellenemedi."):"Profil güncellendi.");setBusy(false)}
  async function changePassword(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setNotice(null);const data=new FormData(event.currentTarget);const response=await fetch("/api/security/change-password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({currentPassword:String(data.get("currentPassword")),newPassword:String(data.get("newPassword"))})});const body=await response.json();setNotice(response.ok?"Parola değiştirildi; diğer oturumlar kapatıldı.":(body.error??"Parola değiştirilemedi."));setBusy(false)}
  async function sessionAction(action:string,token?:string){setBusy(true);setNotice(null);const response=await fetch("/api/security/sessions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,token})});const body=await response.json().catch(()=>({}));if(!response.ok)setNotice(body.error??"İşlem tamamlanamadı.");else if(action==="all")window.location.href="/login";else window.location.reload();setBusy(false)}
  return <div className="account-layout">
    <section className="account-card"><div className="card-title"><span><UserRound size={18}/></span><div><h2>Profil bilgileri</h2><p>Hesabında görünen bilgiler</p></div></div><form className="standard-form" onSubmit={updateProfile}><label>Ad soyad<input name="name" defaultValue={name} required minLength={2}/></label><label>E-posta<input value={email} disabled readOnly/></label><button className="ui-button ui-button-primary" disabled={busy}>Değişiklikleri kaydet</button></form></section>
    <section className="account-card"><div className="card-title"><span><Link2 size={18}/></span><div><h2>Giriş yöntemleri</h2><p>Hesabına bağlı giriş seçenekleri</p></div></div><div className="connection-list">{accounts.map(a=><div key={a.id}><span className="connection-icon">{a.providerId==="credential"?<KeyRound size={17}/>:<strong>G</strong>}</span><div><strong>{a.providerId==="credential"?"E-posta ve parola":"Google"}</strong><small>{a.providerId==="credential"?email:"Google hesabı bağlı"}</small></div><span className="status-badge on">Bağlı</span></div>)}</div>{!accounts.some(a=>a.providerId==="google")&&<button className="ui-button ui-button-neutral" onClick={()=>authClient.linkSocial({provider:"google",callbackURL:"/account"})}>Google hesabını bağla</button>}</section>
    {accounts.some(a=>a.providerId==="credential")&&<section className="account-card"><div className="card-title"><span><KeyRound size={18}/></span><div><h2>Parola değiştir</h2><p>Son 5 parolandan farklı olmalı</p></div></div><form className="standard-form" onSubmit={changePassword}><label>Mevcut parola<input name="currentPassword" type="password" required autoComplete="current-password"/></label><label>Yeni parola<input name="newPassword" type="password" required minLength={12} autoComplete="new-password"/></label><button className="ui-button ui-button-primary" disabled={busy}>Parolayı güncelle</button></form></section>}
    <section id="permissions" className="account-card account-wide"><div className="card-title-row"><div className="card-title"><span><ShieldCheck size={18}/></span><div><h2>Uygulama izinleri</h2><p>Hesabına erişmesine izin verdiğin projeler</p></div></div><span className="app-count-badge">{permissions.length} izin</span></div>{permissions.length?<div className="permission-rows">{permissions.map(p=><div key={p.id}><span className="permission-icon"><AppWindow size={18}/></span><div><strong>{p.name}</strong><small>{scopeNames(p.scopes).join(" · ")}</small></div><span className="permission-date">{new Date(p.updatedAt).toLocaleDateString("tr-TR")}</span><PermissionRevoke consentId={p.id}/></div>)}</div>:<div className="inline-empty"><ShieldCheck size={22}/><div><strong>Paylaşılmış erişim yok</strong><span>Bir uygulamaya izin verdiğinde burada görünecek.</span></div></div>}</section>
    <section id="sessions" className="account-card account-wide"><div className="card-title-row"><div className="card-title"><span><Laptop size={18}/></span><div><h2>Aktif oturumlar</h2><p>Hesabının açık olduğu cihazlar</p></div></div><div className="header-actions"><button className="ui-button ui-button-neutral" disabled={busy} onClick={()=>sessionAction("others")}>Diğerlerinden çık</button><button className="ui-button ui-button-danger" disabled={busy} onClick={()=>sessionAction("all")}>Tümünden çık</button></div></div><div className="session-rows">{sessions.map(s=><div key={s.id}><span className="session-device"><Laptop size={18}/></span><div><strong>{deviceName(s.userAgent)}{s.current&&<em>Bu cihaz</em>}</strong><small>{s.ipAddress??"IP bilinmiyor"} · {new Date(s.createdAt).toLocaleString("tr-TR")}</small></div>{!s.current&&<button className="ui-button ui-button-neutral" disabled={busy} onClick={()=>sessionAction("one",s.token)}>Oturumu kapat</button>}</div>)}</div></section>
    {notice&&<p className="account-notice">{notice}</p>}
  </div>;
}

function deviceName(agent:string|null){if(!agent)return"Bilinmeyen cihaz";const browser=agent.includes("Edg/")?"Edge":agent.includes("Chrome/")?"Chrome":agent.includes("Firefox/")?"Firefox":agent.includes("Safari/")?"Safari":"Tarayıcı";const os=agent.includes("Windows")?"Windows":agent.includes("Mac OS")?"macOS":agent.includes("Android")?"Android":agent.includes("iPhone")?"iPhone":"Cihaz";return`${browser} · ${os}`}
function scopeNames(scopes:string[]){const names:Record<string,string>={openid:"Kimlik",profile:"Profil",email:"E-posta",offline_access:"Oturum yenileme"};return scopes.map(s=>names[s]??s)}
